/*

 BACKGROUND_SCROLLER_ROOM.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 100 x 18
   Tile set      : C:\Users\s189074\Desktop\Complex_Game_Systems\Assets\Gameboy Tile Designer\dungeon_Map_Sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define background_Scroller_MapWidth 100
#define background_Scroller_MapHeight 18
#define background_Scroller_MapBank 0

extern unsigned char background_Scroller_Map[];

/* End of BACKGROUND_SCROLLER_ROOM.H */
