/*

 CHARACTER_WITH_A_HAT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define character_With_A_HatBank 0
/* Start of tile array. */
extern unsigned char character_With_A_Hat[];

/* End of CHARACTER_WITH_A_HAT.H */
