/*

 DUNGEON_ROOM_ONE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\Users\s189074\Desktop\Complex_Game_Systems\Assets\Gameboy Tile Designer\dungeon_Map_Sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define dungeon_Room_OneWidth 32
#define dungeon_Room_OneHeight 32
#define dungeon_Room_OneBank 0

extern unsigned char dungeon_Room_One[];

/* End of DUNGEON_ROOM_ONE.H */
